# Makefile for running Scrapy spider and saving output to JSON

# Variables
SPIDER_NAME = poizonspider
OUTPUT_FILE = poizondata.json

# Targets and Rules
.PHONY: run test

run:
	scrapy crawl $(SPIDER_NAME) -o $(OUTPUT_FILE)


